# Generated by Django 5.1.5 on 2025-04-09 20:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginVerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_verified_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Verification Code",
                "verbose_name_plural": "Login Verification Codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["last_verified_at"],
                        name="dj_rest_aut_last_ve_f66877_idx",
                    ),
                    models.Index(
                        fields=["user", "is_verified"],
                        name="dj_rest_aut_user_id_239c95_idx",
                    ),
                ],
            },
        ),
    ]
